name: release
on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: build
      run: chmod +x ./gradlew && ./gradlew assembleRelease

    - name: get android SDK version
      run: |
        ANDROID_SDK_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "ANDROID_SDK_VERSION=$ANDROID_SDK_VERSION" | tee -a "$GITHUB_ENV"

    - name: sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        alias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASS }}
        keyPassword: ${{ secrets.ANDROID_KEYSTORE_PASS }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.ANDROID_SDK_VERSION }}

    - uses: convco/convco-action@v0.2.0
    - name: convco - bump version
      id: bump
      run: |
        TAG=v$(convco version --bump)
        echo "tag=$TAG" | tee -a "$GITHUB_OUTPUT"
        
    - name: rename artifact
      run: |
        TAG="${{ steps.bump.outputs.tag }}"
        mv "${{steps.sign_app.outputs.signedReleaseFile}}" "boring-browser-$TAG.apk"

    - name: release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG="${{ steps.bump.outputs.tag }}"
        gh release create "$TAG" -t "Release $TAG" "boring-browser-$TAG.apk"
